version: '3.8'

services:
  app:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ilovepython/api:v1.0
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs  # For persistent logs
      - ./.env:/etc/conf/api/.env

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6390:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP port
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=0
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
      - MP_SMTP_AUTH=admin@rcc.com:admin@123
    restart: unless-stopped
volumes:
  postgres_data:
  redis_data: